# TENSORFLOW'S HELLO WORLD

### Installing TensorFlow

In [3]:
!pip install grpcio
!pip install tensorflow

### Importing TensorFlow

In [2]:
import tensorflow as tf
if not tf.__version__ == '2.2.0':
    print(tf.__version__)
    raise ValueError('please upgrade to TensorFlow 2.2.0, or restart your kernel (Kernel ->Restart & Clear Output)')

2.10.0


ValueError: please upgrade to TensorFlow 2.2.0, or restart your kernel (Kernel ->Restart & Clear Output)

### tf.function and AutoGraph

In [4]:
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [5]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [6]:
tf.print(a.numpy()[0])

2


In [7]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms
    print(c)
    return c

In [8]:
result = add(a,b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


### Defining multidimensional arrays using TensorFlow

In [11]:
Scalar = tf.constant(2)
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
Tensor = tf.constant([[[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]],[[7,8,9],[8,9,10],[9,10,11]]])

print('Scalar (1 entry):\n %s \n' % Scalar)

print('Vector (3 entry):\n %s \n' % Vector)

print('Matrix (3x3 entry):\n %s \n' % Matrix)

print('Tensor (3x3x3 entry):\n %s \n' % Tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entry):
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3x3 entry):
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entry):
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



In [12]:
Scalar.shape

TensorShape([])

In [13]:
Tensor.shape

TensorShape([3, 3, 3])

In [15]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

@tf.function
def add():
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    return add_1_operation


print("Defined using tensorflow function :")
add_1_operation = add()
print(add_1_operation)
print("Defined using normal expression :")
add_2_operation = Matrix_one + Matrix_two
print(add_2_operation)

Defined using tensorflow function :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)
Defined using normal expression :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [16]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

@tf.function
def matmul():
    return tf.matmul(Matrix_one, Matrix_two)

mul_operation = matmul()

print("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


### Variables

In [17]:
v = tf.Variable(0)

In [18]:
@tf.function
def increment_by_one(v):
    v = tf.add(v,1)
    return v

In [19]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


### Operations

In [20]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

print('c =: %s' % c)

print('d =: %s' % d)

c =: tf.Tensor([7], shape=(1,), dtype=int32)
d =: tf.Tensor([3], shape=(1,), dtype=int32)
